language: php

php:
  - 5.5
  - 5.6
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer update --dev --no-interaction --prefer-source

script:
  - vendor/bin/phpunit